apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["/bin/sleep", "3650d"]
    imagePullPolicy: IfNotPresent
  restartPolicy: Always




## Una vez instalado, se instala curl
### Acceder al Pod
## kubectl exec -it ubuntu /bin/bash
## apt update
## apt-get upgrade -y

## Estos son los servicios que se estan activos en Kubernetes
#NAME                       TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)           AGE
#hello-kubernetes-service   NodePort    10.96.195.255   <none>        32123:32491/TCP   9m29s
#kubernetes                 ClusterIP   10.96.0.1       <none>        443/TCP           10m

## curl 10.96.195.255:32123

