kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader-binding
  namespace: accounting
subjects:
# IAM service account
- kind: User
  name: demo-roles-sa@alan-sandbox-393620.iam.gserviceaccount.com
roleRef:
  kind: Role
  name: pod-reader-creator
  apiGroup: rbac.authorization.k8s.io